[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#f5e0dc"
text = "#1e1e2e"

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[font]
size = 16

[font.bold]
family = "Terminess Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Terminess Nerd Font Mono"
style = "BoldItalic"

[font.normal]
family = "Terminess Nerd Font Mono"
style = "Regular"

[terminal.shell]
program = "/bin/fish"

[window]
opacity = 0.8

[terminal]
